export enum ItemsListTypes {
    ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
    REMOVE_ALL_ITEMS = 'REMOVE_ALL_ITEMS',
    LOAD_PRODUCTS = "LOAD_PRODUCTS",
    REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART',
    REMOVE_ALL_ITEMS_FROM_CART = 'REMOVE_ALL_ITEMS_FROM_CART',
    UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART',
    UPDATE_PRODUCT_LIMIT = 'UPDATE_PRODUCT_LIMIT',
    Add_ITEM_TO_FAVORITES = 'Add_ITEM_TO_FAVORITES',
    REMOVE_ITEM_FROM_FAVORITES = 'REMOVE_ITEM_FROM_FAVORITES',
}