export enum ItemsListTypes {
    LOAD_PRODUCTS='LOAD_PRODUCTS',
    ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART',
    REMOVE_ALL_ITEMS_FROM_CART = 'REMOVE_ALL_ITEMS_FROM_CART',
    UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART',
    UPDATE_PRODUCT_LIMIT = 'UPDATE_PRODUCT_LIMIT'
}